### ISSUE TITLE
Implement wallpaper's engine texture format

### ISSUE THREAD

**Issue by Almamu** [Almamu/linux-wallpaperengine#1]
Most of the format is already reversed by me here: https://github.com/Almamu/linux-wallpaperengine/blob/master/docs/TEXTURE_FORMAT.md
The next, logical step, would be to implement proper texture loading to not rely on .png/.jpg files (as it is right now, we get the texture name and search for the jpg/png file with that same name, but all the wallpapers stored in the steam store do not include any).

**Comment by lhy0403** [comment]
https://github.com/notscuffed/repkg

I found @notscuffed has a project doing something (maybe) related, FYI.

**Comment by Almamu** [comment]
Yeah, that project pretty much does the extraction of textures, which includes the whole file format used. It confirms most of the reverse I did on the format already, so that a plus. Hopefully I can finish the implementation this week.

**Comment by Almamu** [comment]
First work on this has been implemented. The ARGB88888 format is supported (which is the only one used in the test background right now), with more coming soon.
82682ecf02febfce8c6f298028f93fdef132b1eb
0b424ac5f4f4046729f35f94c4e53005cd79b2b4
ae9665772a10862cd9b1f83de927f8ba8dd697a6

**Comment by Almamu** [comment]
Support for this is completely implemented on the opengl-port branch, being the commit 213af7b99adaa05c17a9f302abdd68c2a5d9d2bd the one that brings it up to feature parity with the irrlicht version, with improvements on shader handling which make more backgrounds work.
