### ISSUE TITLE
Cannot initialize SDL audio system

### ISSUE THREAD

**Issue by bennybenjaman** [Almamu/linux-wallpaperengine#10]
Debian testing

Installed deps including 

- libsdl-mixer1.2
- libsdl2-2.0-0

Output when I run a background  from a directory 

Irrlicht Engine version 1.8.4
Linux 5.2.17-rt7 #1 SMP Tue Oct 22 07:22:41 MDT 2019 x86_64
Using renderer: OpenGL 3.1
AMD BARTS (DRM 2.50.0 / 5.2.17-rt7, LLVM 9.0.0): X.Org
OpenGL driver version is 1.2 or better.
GLSL version: 1.4
Cannot initialize SDL audio system

I have also tried running as sudo

**Comment by Gamerstone** [comment]
I don't know if this wall help but on arch I had to install the 32bit version of sdl

**Comment by Almamu** [comment]
What is the output of ```dpkg --list | grep sdl```? Take in mind that you need SDL (not SDL2) and SDL_mixer. I guess your installation is x64? I'll try to build it in debian testing as soon as I have time and get back to you.

**Comment by themultiplexer** [comment]
I got the same issue on Debian Buster (NVdia Graphics card). Would really love to see it work!

**Comment by Almamu** [comment]
@themultiplexer I'll need some extra information on why this happens. Can you run ```dpkg --list | grep sdl``` and copy the output here? I guess you're using the 64 bit version of debian?

**Comment by themultiplexer** [comment]
I actually fixed the problem tonight:
I found out that `MixInit()` returns error code 9 which means: `Mixer not built with MP3 support`

So i pulled SDL_mixer and compiled it myself:
If _libmpg123_ is found, SDL_mixer automatically compiles with MP3 support.
```bash
hg clone http://hg.libsdl.org/SDL_mixer/
hg checkout SDL-1.2
sudo apt install libmpg123-dev
mkdir build
cd build
../configure
make
sudo make install
```

Finally I had to add the SDL header path to `CMakeLists.txt` so it finds SDL_types.h, etc.
```
set(SDL_INCLUDE_DIRS /usr/include/SDL)
```

I hope this fix works for you @bennybenjaman

**Comment by Almamu** [comment]
That's a little weird. I'm adding some extra information to the "Cannot initialize SDL audio system" so It's easier to debug in the future, and I'll investigate why the debian's SDL-mixer doesn't support MP3. I'll keep the issue open for now so I can at least update the compilation instructions.

**Comment by ambidot** [comment]
I had success with removing the system libsdl-mixer1.2 and libsdl-mixer1.2-dev and instead installing binaries from https://www.libsdl.org/projects/SDL_mixer/release-1.2.html with `alien` and dpkg. This seems to be easier than rewriting linux-wallpaperengine to use SDL_mixer 2.0.

Linux Mint 20

**Comment by staticnation** [comment]
`static@Blackstar:~/.git/linux-wallpaperengine/build$ ./wallengine -pkg /home/static/.steam/steam/steamapps/workshop/content/431960/1899258427/scene.pkg
Irrlicht Engine version 1.8.4
Linux 5.7.10-xanmod1 #0~git20200722.ed358d3 SMP PREEMPT Wed Jul 22 12:07:44 UTC 2020 x86_64
Using renderer: OpenGL 4.6
Radeon RX 580 Series (POLARIS10, DRM 3.37.0, 5.7.10-xanmod1, LLVM 10.0.1): X.Org
OpenGL driver version is 1.2 or better.
GLSL version: 4.6
Could not create archive for: /home/static/.git/linux-wallpaperengine/build/kgscene.pkg
Cannot initialize SDL audio system: Mixer not built with MP3 support`


`static@Blackstar:~/.git/linux-wallpaperengine/build$ dpkg --list | grep sdl
ii  libsdl-console:amd64                       2.1-6                                                      amd64        Console that can be added to any SDL application, libraries
ii  libsdl-gfx1.2-5:amd64                      2.0.25-11                                                  amd64        drawing and graphical effects extension for SDL
ii  libsdl-image1.2:amd64                      1.2.12-12                                                  amd64        Image loading library for Simple DirectMedia Layer 1.2, libraries
ii  libsdl-image1.2:i386                       1.2.12-12                                                  i386         Image loading library for Simple DirectMedia Layer 1.2, libraries
ii  libsdl-kitchensink1:amd64                  1.0.7-1                                                    amd64        FFmpeg and SDL2 based library for audio and video playback
ii  libsdl-mixer1.2:amd64                      1.2.12-16build1                                            amd64        Mixer library for Simple DirectMedia Layer 1.2, libraries
ii  libsdl-mixer1.2:i386                       1.2.12-16build1                                            i386         Mixer library for Simple DirectMedia Layer 1.2, libraries
ii  libsdl-mixer1.2-dev:amd64                  1.2.12-16build1                                            amd64        Mixer library for Simple DirectMedia Layer 1.2, development files
ii  libsdl-net1.2:i386                         1.2.8-6                                                    i386         Network library for Simple DirectMedia Layer 1.2, libraries
ii  libsdl-sge:amd64                           030809dfsg-9                                               amd64        extension of graphic functions for SDL multimedia libraries
ii  libsdl-sound1.2:amd64                      1.0.3-9                                                    amd64        Sound library for Simple DirectMedia Layer 1.2, libraries
ii  libsdl-ttf2.0-0:i386                       2.0.11-6                                                   i386         TrueType Font library for Simple DirectMedia Layer 1.2, libraries
ii  libsdl1.2-dev                              1.2.15+dfsg2-5                                             amd64        Simple DirectMedia Layer development files
ii  libsdl1.2debian:amd64                      1.2.15+dfsg2-5                                             amd64        Simple DirectMedia Layer
ii  libsdl1.2debian:i386                       1.2.15+dfsg2-5                                             i386         Simple DirectMedia Layer
ii  libsdl2-2.0-0:amd64                        2.0.10+dfsg1-3                                             amd64        Simple DirectMedia Layer
ii  libsdl2-2.0-0:i386                         2.0.10+dfsg1-3                                             i386         Simple DirectMedia Layer
ii  libsdl2-dev:amd64                          2.0.10+dfsg1-3                                             amd64        Simple DirectMedia Layer development files
ii  libsdl2-gfx-1.0-0:amd64                    1.0.4+dfsg-3                                               amd64        drawing and graphical effects extension for SDL2
ii  libsdl2-image-2.0-0:amd64                  2.0.5+dfsg1-2                                              amd64        Image loading library for Simple DirectMedia Layer 2, libraries
ii  libsdl2-mixer-2.0-0:amd64                  2.0.4+dfsg1-2build1                                        amd64        Mixer library for Simple DirectMedia Layer 2, libraries
ii  libsdl2-mixer-dev:amd64                    2.0.4+dfsg1-2build1                                        amd64        Mixer library for Simple DirectMedia Layer 2, development files
ii  libsdl2-net-2.0-0:amd64                    2.0.1+dfsg1-4                                              amd64        Network library for Simple DirectMedia Layer 2, libraries
ii  libsdl2-ttf-2.0-0:amd64                    2.0.15+dfsg1-1                                             amd64        TrueType Font library for Simple DirectMedia Layer 2, libraries
`

**Comment by BlackHawk185** [comment]
Old thread but I'm experiencing this issue as well.

**Comment by mumboFromAvnotaklu** [comment]
do not that libsdl-mixer1.2 requires libsmpeg-dev for mp3 support 
whereas libsdl2-mixer requires libmpeg123

**Comment by Nova1545** [comment]
Im getting the same error where SDL Mixer isnt built with mp3 support, is there a fix for this or a guide to building SDL Mixer with mp3 support?

**Comment by Almamu** [comment]
> Im getting the same error where SDL Mixer isnt built with mp3 support, is there a fix for this or a guide to building SDL Mixer with mp3 support?

I don't have any guides to build SDL_Mixer for ubuntu. SDLmixer is not a really complex library, so it should be somewhat easy to do. Check their release page and the documentation they have on the build process, that should get you started: https://www.libsdl.org/projects/SDL_mixer/release-1.2.html

**Comment by Almamu** [comment]
This issue is irrelevant now. SDL 1.2 is no longer in use. There's still issues with audio, but because of different reasons.
