### ISSUE TITLE
Feature Request: Open background by ID instead of full path

### ISSUE THREAD

**Issue by mihawk90** [Almamu/linux-wallpaperengine#101]
Currently, opening a background requires passing the entire path to the background assets directory like this:
```bash
./wallengine /entire/path/to/background/directory/by/id/1845706469/
```

This request is for a way to call LWE by simply calling the ID and nothing else, like this:
```
./wallengine 1845706469
```

Since aa3db15ec63a1d15f8d4de42ea976e90d741d183 added auto-detection for the base WE assets, the same path can be re-used to find the background assets.
From what I can tell, Steam always keeps WE, its assets, and the corresponding Workshop items in the same Steam Library. So even if the user has set up multiple libraries and moves WE between them, the Workshop items should be moved alongside them.

The default path is `~/.steam/steam/steamapps/workshop/content/431960/2685564485/` where 431960 is just the application ID for WE, so it's static.

Ideally, LWE would autodetect if an entire path was provided or just the ID and go from there accordingly. The usecase of having backgrounds elsewhere entirely shouldn't be lost after all.

**Comment by Almamu** [comment]
This should be implemented in the last commit 46ea8e8f03ffb992b37e3cffc86f276a4a50cf69
