### ISSUE TITLE
Allow Linux-Wallpaper Engine to manage background on Gnome 42 (X11)

### ISSUE THREAD

**Issue by Nova1545** [Almamu/linux-wallpaperengine#104]
Attempted to run this as a wallpaper the other day. I tried a few things and google a bunch of stuff, nothing seemed to allow it set the wallpaper. 
Ive tried:
- Uninstalling nautilus
- Setting the current wallpaper to a fully transparent one
- Other suggestions to stop nautilus from managing the wallpaper

None of these have worked. Is there something specific I need to do to stop gnome from drawing the wallpaper?

**Comment by Almamu** [comment]
As of now there's no known workaround to have GNOME stop drawing to the background. It used to be possible to recompile nautilus to exclude that, but I don't know if it's possible anymore. Progress on this issue is being tracked on #8
