### ISSUE TITLE
WE doesn't quit when using 1517243732

### ISSUE THREAD

**Issue by mihawk90** [Almamu/linux-wallpaperengine#107]
This is a bit of an odd issue and the first time I ran across this.

Using [1517243732](https://steamcommunity.com/sharedfiles/filedetails/?id=1517243732), it renders just fine (from what I can tell anyway), but after closing the window, the process still hangs around and can't be shut down via Ctrl+c either, I need to actively kill the process via system monitor.

I also sanity checked against various other backgrounds and none of them are exhibiting this behaviour.

Not sure where to even start debugging this :thinking:

**Comment by Almamu** [comment]
This situation seemed to be caused by the audio thread running in the background. I've fixed it so now it should stop just fine by itself.
