### ISSUE TITLE
[BGFIX] Unexpected type for property

### ISSUE THREAD

**Issue by UltraBlackLinux** [Almamu/linux-wallpaperengine#115]
**Wallpaper Engine Background(s)**
2370927443

**Console output**

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unexpected type for property
```

**Desktop (please complete the following information):**
 
- OS: [e.g. Arch Linux]
 - Desktop Environment: Wayfire
 - Window Manager: Wayfire

**Comment by Almamu** [comment]
I've done some work on fixing this background, but hit a dead end for now due to how it's shader code looks like. There's a modulo operation that is not supported in GLSL for which I'll need to add some extra code to detect. Hopefully I'll get to this one in the next couple of days.

**Comment by Almamu** [comment]
Closing in favor of #124 as it's about the same background
