### ISSUE TITLE
Which name to use to create a package

### ISSUE THREAD

**Issue by rapenne-s** [Almamu/linux-wallpaperengine#125]
Hi! I'm currently packaging this software but I'm not sure which name I should give it.

Right now, I have a few ideas in mind:

- linux-wallpaperengine
- linux-wallpaper-engine
- wallpaperengine
- wallpaper-engine
- wallpaper (the name of the binary)

**Comment by Nova1545** [comment]
Perhaps linux-wallpaper-engine? Seeing as all 3 are different words

**Comment by Almamu** [comment]
@rapenne-s Sorry for the late reply, ideally the package should be named exactly the same as the binary, but I do think that wallengine (the name of the binary) is a bit non-descriptive and hard to understand unless you really know what you're looking for.

Personally, I'd go for ```linux-wallpaperengine``` for both package and binary, so it also match with the repository name. I'll commit a change with the binary rename (and a fallback for the old name so it doesn't break anyone that uses it).

Just out of curiosity, what distro are you planning on packaging it for?

**Comment by rapenne-s** [comment]
Thank you!

It's a package for https://github.com/NixOS/nixpkgs/

**Comment by rapenne-s** [comment]
https://github.com/NixOS/nixpkgs/pull/188136
