### ISSUE TITLE
[BGFIX] Unsupported package version: PKGV0017

### ISSUE THREAD

**Issue by UltraBlackLinux** [Almamu/linux-wallpaperengine#127]
**Wallpaper Engine Background(s)**

2852314079
and many more - most of the ones on the workshop front page suffer from this

**Console output**
```
Failed to load scene.pkg file: Unsupported package version: PKGV0017
terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot load package file
```

**Desktop (please complete the following information):**
 
- OS: Arch Linux
 - Desktop Environment: wayfire
 - Window Manager: wayfire

**Comment by Almamu** [comment]
Sorry, forgot to comment on this. PKGV0017 should load now. The background in this instance doesn't display properly as there seems to be some shader issues going on.

**Comment by rombix** [comment]
i think it comes with it:
`./linux-wallpaperengine 2362055586
Failed to load scene.pkg file: Unsupported package version: PKGV0011
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to load scene.pkg file: Unsupported package version: PKGV0011
Aborted (core dumped)
`

**Comment by trainzkid** [comment]
@Almamu this issue should be fixed now, thanks to the PKGV validation rewrite, correct?

**Comment by Almamu** [comment]
> @Almamu this issue should be fixed now, thanks to the PKGV validation rewrite, correct?

Yes, closing this one too.
