### ISSUE TITLE
Ffmpeg not found

### ISSUE THREAD

**Issue by PistachioGuy** [Almamu/linux-wallpaperengine#134]
When I try to compile it I get this error.

-- Found LZ4: /usr/lib/x86_64-linux-gnu/liblz4.so
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:226 (message):
  No REQUIRED_VARS specified for FIND_PACKAGE_HANDLE_STANDARD_ARGS()
Call Stack (most recent call first):
  CMakeModules/FindFFMPEG.cmake:23 (find_package_handle_standard_args)
  CMakeLists.txt:19 (find_package)

-- Configuring incomplete, errors occurred!

I'm on Zorin os 16.2. ffmpeg is installed, 

IdeaPad-3-15ARE05:~/linux-wallpaperengine/build$ sudo apt install ffmpeg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ffmpeg is already the newest version (7:4.2.7-0ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.

**Comment by Svallinn** [comment]
https://github.com/Almamu/linux-wallpaperengine/issues/121#issuecomment-1194911528

**Comment by PistachioGuy** [comment]
I updated cmake and it worked, thanks.

**Comment by PistachioGuy** [comment]
Ubuntu "stability" moment
