### ISSUE TITLE
Cmake cannot find LZ4

### ISSUE THREAD

**Issue by Th1ngP3rs0n** [Almamu/linux-wallpaperengine#135]
When I go to generate the makefiles (with cmake ..) I keep getting some error about cmake not being able to find lz4. I've tried downloading the newest versions of lz4, liblz4-1, and liblz4-dev and nothing changed. I have also updated from cmake 24.2 to 25.1, which also didn't work.

> CMake Error at /snap/cmake/1210/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find LZ4 (missing: LZ4_GOOD_VERSION)
Call Stack (most recent call first):
  /snap/cmake/1210/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  CMakeModules/FindLZ4.cmake:31 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:18 (find_package)
-- Configuring incomplete, errors occurred!
See also "/home/th1ngp3rs0n/linux-wallpaperengine-main/build/CMakeFiles/CMakeOutput.log".
See also "/home/th1ngp3rs0n/linux-wallpaperengine-main/build/CMakeFiles/CMakeError.log".

I'm not really sure what to do and so some help would be greatly appreciated!

**Comment by Almamu** [comment]
Can you share the logs created by CMake to see what it's exactly looking for? That should give us some more information on what's going on...

**Comment by sud0cs** [comment]
Hi, I had the same issue and I was able to solve it by running `sudo apt -y install liblz4-dev`
