### ISSUE TITLE
Make Error(Linking CXX executable linux-wallpaperengine)

### ISSUE THREAD

**Issue by PatekGao** [Almamu/linux-wallpaperengine#136]
Cmake .. was done successfully, but when I make it, an error occered.(cmake again didn't solve this error)
![Screenshot from 2022-12-16 13-25-25](https://user-images.githubusercontent.com/99338120/208028577-22b7da2b-9ea2-4647-8fd2-da96bbd1ad6e.png)

**Comment by PatekGao** [comment]
OS is Ubuntu 20.04.5 LTS x86_64 
CMake version is 3.25.0

**Comment by Almamu** [comment]
Can you re-run the make command adding the verbose option like this?
```make VERBOSE=1```

**Comment by C5807** [comment]
> Can you re-run the make command adding the verbose option like this? `make VERBOSE=1`

Hello, I have the same error. Here is the output of make after adding the verbose option (and I apologize for some of it is not in your language)

https://pastebin.com/rfY9zTK1

**Comment by Almamu** [comment]
> > Can you re-run the make command adding the verbose option like this? `make VERBOSE=1`
> 
> Hello, I have the same error. Here is the output of make after adding the verbose option (and I apologize for some of it is not in your language)
> 
> https://pastebin.com/rfY9zTK1

In your case either you installed freeimage after running cmake, or the freeimage libs cannot be found. Make sure you have installed the development and normal packages of freeimage available on your distribution.

**Comment by jabuxas** [comment]
that was my exact issue ty. cmake before installing freeimage
