### ISSUE TITLE
Feature Request: Add wlroots support to linux-wallpaper engine

### ISSUE THREAD

**Issue by camatthew** [Almamu/linux-wallpaperengine#137]
If we make this compatible with wlroots desktops and make it draw on the background layer, it should be able to support any linux desktop environment / compositor based on wlroots.

**Comment by Almamu** [comment]
Currently theres no support for Wayland implemented at all (and I don't use wayland myself either) so I don't really know where to begin... I'll definetly take a look sometime in the future.

**Comment by vaxerski** [comment]
I could write a Wayland impl, however I am unsure whether we should use [wlr-layer-shell-v1](https://gitlab.freedesktop.org/wlroots/wlr-protocols/-/blob/master/unstable/wlr-layer-shell-unstable-v1.xml) which is supported in wlroots and KDE, but not Guhnome, or wait for [ext-layer-shell-v1](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/28)

**Comment by vaxerski** [comment]
Looking at the glfw mr and stuff, it seems like they're planning to take a very reasonable approach and plan out the thing to be more x-platform, which might take some time.

We don't need that here, so if @Almamu is interested in getting this done, I can have a stab at writing a Wayland driver manually myself. Pretty sure that the Wayland driver would have to be glfw-free, though.

**Comment by Almamu** [comment]
@vaxerski Sure, PR are always welcome!

There's some challenges that I'm not sure how we could solve that might need some thought before starting a Wayland implementation:
- Should we require both GLFW and Wayland libs on build time? Or just build for one based on user selection? Any legitimate reason to have a build with support for both?
- How do we switch between drivers if we build with support for both?
- What about the X11-specific code?

I don't have much experience with these as usually libraries like SDL2 or GLFW do handle it, and packaging also needs to be taken into account for the build system. Ideally one package would cover both X11 and Wayland without the need of rebuilding...
