### ISSUE TITLE
Cannot find workshop directory for steam app 431960 and content 2928173801

### ISSUE THREAD

**Issue by vladserebryakov** [Almamu/linux-wallpaperengine#141]
Cannot find workshop directory for steam app 431960 and content 2928173801
terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot find workshop directory for steam app 431960 and content 2928173801
Аварийный останов (стек памяти сброшен на диск)

**Comment by Almamu** [comment]
Hi @vladserebryakov, under what path is the steam workshop content stored? Currently the app only looks into the following directories:
~/.steam/steam/steamapps/workshop/content
~/.local/share/Steam/steamapps/workshop/content

**Comment by vladserebryakov** [comment]
Sorry it was my mistake, I forgot to find the assets folder, sorry for the discovery

**Comment by illegitimate-egg** [comment]
Hi, this is definitely still a problem. I have the assets folder located next to the binary and manually overriden using a flag. My steam is installed at /mnt/D/Steam. There is no way for me to change where it looks for workshop content, which to me seems like a huge issue
