### ISSUE TITLE
Fullscreen triggers picoms fullscreen detection and turns off compositing

### ISSUE THREAD

**Issue by Crylia** [Almamu/linux-wallpaperengine#144]
Title

**Comment by Crylia** [comment]
Actually it only happened once for the first time I started it, maybe it was related to the wallpaper? I can't reproduce it anymore

**Comment by trainzkid** [comment]
@Crylia can you triple check with the latest version? If this no longer occurs, I think this issue can be closed.

**Comment by Crylia** [comment]
Sadly I can't test it anymore, but I know that it never happened again, maybe it was a problem with my config
