### ISSUE TITLE
Starts lagging the wm and clients heavily after some time

### ISSUE THREAD

**Issue by Crylia** [Almamu/linux-wallpaperengine#145]
I can't quiet reproduce it but after some time clients and the wm (in my case AwesomeWM) start laggin heavily

awesome-git
NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7

**Comment by trainzkid** [comment]
@Crylia is this still occurring with the latest version? Which specific wallpapers does it occur on?

**Comment by Crylia** [comment]
I can't test it anymore sadly, I would close it and reopen if someone happens to have the same problem I once had.
