### ISSUE TITLE
[BGFIX]

### ISSUE THREAD

**Issue by triston-li** [Almamu/linux-wallpaperengine#148]
**Wallpaper Engine Background(s)**

Link(s) to the background(s) in the steam workshop or their background ID(s).
Pretty much any background I'm trying is giving me this error (ex: 793602574, 864286576)

```
Cannot find directory for steam app wallpaper_engine: assets
No "scene.pkg" file found at "/home/user/build/793602574/scene.pkg". Defaulting to normal folder storage
No "gifscene.pkg" file found at "/home/user/build/793602574/gifscene.pkg". Defaulting to normal folder storage
Cannot find "". This folder is required for wallpaper engine to work
terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot find "". This folder is required for wallpaper engine to work
Aborted (core dumped)
```
It seems to be missing an "" folder, but even after creating the same named folder within the background folder it's still not working and I'm unsure of which folder it may be referring to as the name seems to be blank(?).

**Desktop (please complete the following information):**
 
- OS: Pop_OS! 22.04 LTS

**Additional context**

I've compiled the program but it was having some issues finding the steam workshop files, so I manually cloned the files into the "build" folder, so my file paths are manually added into the terminal commands. It seems to be able to find the wallpapers but it's hitting the mentioned snag. Thanks so much for the help and I really appreciate the time you've put into creating this program!

**Comment by Almamu** [comment]
You should be specifying the assets folder with the ```--assets-dir``` argument so the software knows where to find the files if you don't have Steam and Wallpaper Engine installed.

**Comment by pwfff** [comment]
I'm getting the same thing with the first wallpaper I tried after installing via the [AUR](https://aur.archlinux.org/packages/linux-wallpaperengine-git):
```
[pwf@prism ~]$ ls .local/share/Steam/steamapps/workshop/content/431960/2943621120/
 preview.gif   project.json  'the drive by visualdon.mp4'
[pwf@prism ~]$ linux-wallpaperengine 2943621120
No "scene.pkg" file found at "/home/pwf/.local/share/Steam/steamapps/workshop/content/431960/2943621120/scene.pkg". Defaulting to normal folder storage
No "gifscene.pkg" file found at "/home/pwf/.local/share/Steam/steamapps/workshop/content/431960/2943621120/gifscene.pkg". Defaulting to normal folder storage
Cannot find "../share/". This folder is required for wallpaper engine to work
terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot find "../share/". This folder is required for wallpaper engine to work
Aborted (core dumped)
[pwf@prism ~]$ cat .local/share/Steam/steamapps/workshop/content/431960/2943621120/project.json
{

...

	"preview" : "preview.gif",
	"tags" : [ "Retro" ],
	"title" : "The Drive by Visualdon - Remastered, 4K 60fps",
	"type" : "video",
	"version" : 0
}
```

Binary was in `/usr/bin`, and I tried linking `assets` to both `/usr/bin/assets` and `/usr/share/assets` to no avail. Maybe it wanted `/home/share`...?

Anyways, I checked this out, compiled from source, and linked `assets` to `./build/assets` and it works :shrug:

**Comment by Almamu** [comment]
I've pushed a fix that should improve the situation with the ../share/ folder, but looks like the PKGBUILD of that package needs to be fixed to include the share folder in the installation process. I've commented on it and hopefully the maintainer fixes it.

**Comment by Almamu** [comment]
I've taken ownership of the AUR's package and should be properly building now.
