### ISSUE TITLE
Attempting to run linux-wallpaperengine at boot produces: Failed to initialize glfw

### ISSUE THREAD

**Issue by digitaltapestryposters** [Almamu/linux-wallpaperengine#149]
Hi, I am currently working on a client-server project utilizing linux-wallpaperengine, where the server a script starts at boot that listens for the id of the background that the user would like to use. However, when the id is received the background doesn't change and checking the /proc/{pid}/fd/1 shows: 

`
Cannot find required key (distancemin) in json: Particle emitter must have minimum distance
Failed to initialize glfw
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to initialize glfw
`

Other wise when the server starts from terminal everything works fine. Would it be failing because the script starts too early before light dm starts up? Ive attempted to have it start later but that has not worked either. Essentially my question is "is wallpaper engine failing because it is starting too early or because it is being ran from a process?"

Thanks for your help ahead of time. If you need more information or I haven't been clear please let me know.

**Comment by Almamu** [comment]
I'm not really sure of what the situation might be. The first thing that comes to mind is not having an X11 display available because of the way you're running it (you can usually check the $DISPLAY variable).

I've added some extra error handling to GLFW, hopefully that gives more insight into what's happening here.

**Comment by digitaltapestryposters** [comment]
Thank you for your help! I managed to figure it out earlier where it did have to have the correct environment variables available. As for the particular one that it needs im not sure since I just copied the environ of the window manager such as i3 over to the script running the engine and it worked from there.
