### ISSUE TITLE
getpid() was not declared in this scope during compiliation

### ISSUE THREAD

**Issue by digitaltapestryposters** [Almamu/linux-wallpaperengine#155]
Hi I am attempting to compile linux-wallpaper engine on Debian and I get the following error: 
`
src/WallpaperEngine/Audio/Drivers/Detectors/CPulseAudioPlayingDetector.cpp:19:29: error: ‘getpid’ was not declared in this scope; did you mean ‘getpt’?
   19 |         if (atoi (value) != getpid () && pa_cvolume_avg (&info->volume) != PA_VOLUME_MUTED)
      |                             ^~~~~~
`
during compilation. I have a work around where I add `#include <unistd.h>` to the top of the file but idk if this the correct solution.

Just thought I would let you know

**Comment by Almamu** [comment]
Yes, that should be the right solution. I'll make a commit with your fix. Weirdly didn't come up on the Ubuntu builds 😅
