### ISSUE TITLE
Background freezes when any window in full-screen (multiple monitors)

### ISSUE THREAD

**Issue by Nicolas-Reyland** [Almamu/linux-wallpaperengine#157]
I have two monitors. The app works just fine, except when any window is in full-screen mode (`mod+f` on `i3`). The wallpaper freezes on both monitors.

**Comment by Almamu** [comment]
There's code to detect when a windows is fullscreen just like the normal wallpaperengine. I've added a command line argument in the last commit to disable this check and exposed it in the help too:
```
linux-wallpaperengine --no-fullscreen-pause BACKGROUND
``` 
should prevent this from happening again.
