### ISSUE TITLE
[Regression] Performance of scenes drops to 1FPS.

### ISSUE THREAD

**Issue by vaxerski** [Almamu/linux-wallpaperengine#158]
After b69ce8ba577d17ff4281f310176d3a14b934dae4 the performance of scenes drops to ~1FPS on my system. Previously, it's solid. Both Xorg (thru Xephyr) and XWayland.

Worth noting that's in `NORMAL_WINDOW` mode.

Tested with further commits, but it's odd:
 - In Xorg, it's a still picture
 - In XWayland, many further commits literally make XWayland shit itself, as in, it will no longer open the window until I do a ctrl+c in the terminal, when the window opens and closes instantly.
 
 Some further commit seems to fix number 2, but it's a pain to verify which, with the addition that many intermittent commits segfault instantly on launch.
 
It probably is a driver issue, possibly some focus detection?

**Comment by Almamu** [comment]
Can you try to run the last commit available with the argument ```--no-fullscreen-pause``` and see if the issue persist?

That should disable the checks for other apps being full screen and is the only thing that might be making the app go so slow...

**Comment by vaxerski** [comment]
`--no-fullscreen-pause` does not change anything, it seems. Still 1 fps.

Putting a log on swapBuffers: indeed, one swap per second.

**Comment by vaxerski** [comment]
Narrowed down: `CPulseAudioPlaybackRecorder::update` is extra slow.

**Comment by Almamu** [comment]
Could be the calls to ```pa_mainloop_update``` as they block until something is ready to process, if you're not using pulse there won't be anything to process and block. Blocking should not happen anymore, can you test it with this change? 37b40ec29f97a75bb2b3ddcb41843735b30a5e70

**Comment by vaxerski** [comment]
Seems to be fixed. Thanks!
