### ISSUE TITLE
[BGFIX] Water caustics/reflections? apply to whole Background instead of just the puddle 

### ISSUE THREAD

**Issue by Teddy-Kun** [Almamu/linux-wallpaperengine#161]
**Wallpaper Engine Background(s)**
[1478390341](https://steamcommunity.com/sharedfiles/filedetails/?id=1478390341)

**Console output**

https://pastebin.com/aCadrzqC

**Screenshots**
For Windows just look at the image on the Steam workshop

Linux:
![20230424_21h53m10s_grim](https://user-images.githubusercontent.com/58993831/234101655-22e90e77-a896-4295-8f6b-987e86c31c67.png)

**Desktop (please complete the following information):**
 
- OS: Arch Linux
 - Desktop Environment: Hyprland
 I only tested it in windowed mode so the DE should not matter.

**Additional context**
I run Mesa 23.1.0-rc2 on a 7900XT

**Comment by Almamu** [comment]
Should be fixed now.
