### ISSUE TITLE
Does not compile #include <cstdint> missing

### ISSUE THREAD

**Issue by Teddy-Kun** [Almamu/linux-wallpaperengine#162]
Like title said it does not compile on my system (Arch Linux with Mesa-git).
Adding `#include <cstdint>` at the top of `src/External/Android/fft.h` fixes it.
I have included the error I get below.

[linux_wallpaperengine_compile_error.txt](https://github.com/Almamu/linux-wallpaperengine/files/11415622/linux_wallpaperengine_compile_error.txt)

**Comment by Almamu** [comment]
The include is there, but I've moved it to fft.h as there's some usage of uint8_t there. I find it weird that I don't have any issue with it on my local arch tho, wonder why....

**Comment by Teddy-Kun** [comment]
Can confirm 660f798 fixed the issue.
