### ISSUE TITLE
[BGFIX], only background and the audio visualizer seem to show up.

### ISSUE THREAD

**Issue by m3t4f1v3** [Almamu/linux-wallpaperengine#165]
**Console output**

[output.txt](https://github.com/Almamu/linux-wallpaperengine/files/11591452/output.txt)

**Screenshots**
[Lofi cafe](https://steamcommunity.com/sharedfiles/filedetails/?id=2370927443)
![Screenshot_20230529_214725](https://github.com/Almamu/linux-wallpaperengine/assets/40429600/c3321eda-b5b9-42fa-a9ac-caa70e20e0c3)
[Umineko no naku koro ni](https://steamcommunity.com/sharedfiles/filedetails/?id=2814721615)
![Screenshot_20230529_215321](https://github.com/Almamu/linux-wallpaperengine/assets/40429600/47ff5c1f-a168-4756-bac5-681507f6a5db)

**Desktop**
 
- OS: Arch Linux
 - Desktop Environment: KDE
 - Window Manager: Plasma
 - Compositor: picom

**Additional context**
My gpu is an RX570, I'm using meta-tkg-git and I've installed the latest version from your AUR package (linux-wallpaperengine-git)
My console command was `linux-wallpaperengine --assets-dir /media/Games/SteamLibrary/steamapps/common/wallpaper_engine/assets/ /media/Games/SteamLibrary/steamapps/workshop/content/431960/2814721615/`

**Comment by Almamu** [comment]
This should be fixed with the latest commits. Wallpaper Engine made an update that introduced new ways of calculating color values for images that we didn't support yet.
