### ISSUE TITLE
Pixels stretched if WP resolution is different to screen resolution

### ISSUE THREAD

**Issue by UltraBlackLinux** [Almamu/linux-wallpaperengine#173]
![image](https://github.com/Almamu/linux-wallpaperengine/assets/62404294/509a2c62-5cfa-4d28-aff4-bce6ea2d2e2c)

What about a scale-to-fit or crop option for this? I'm on wayland, using the layer-shell protocol, if that matters

**Comment by Almamu** [comment]
I'll look into this, scaling should already be taking care of this, but it might be missing something in the logic.

**Comment by Teddy-Kun** [comment]
I can confirm the stretching behavior.
![20230830_11h12m21s_grim](https://github.com/Almamu/linux-wallpaperengine/assets/58993831/2276a560-cb73-41d3-8e73-14e30a7e5311)

**Comment by Pasalc** [comment]
@UltraBlackLinux @Teddy-Kun could you check if my pull request work for you?
