### ISSUE TITLE
Instantaneous segfault on startup

### ISSUE THREAD

**Issue by neomoth** [Almamu/linux-wallpaperengine#181]
The window for the program appears for about a full second before crashing from a segfault. Window does not refresh before closing, so it appears as though the content is transparent, that's how early on it's failing.
![image](https://github.com/Almamu/linux-wallpaperengine/assets/69372252/405dba95-5e5c-4878-bf73-da43c41b401c)

### Relevant System Configuration Info
- Kernel: Arch 6.4.12-arch1-1

**Comment by trainzkid** [comment]
Does it work if you specify a wallpaper ID? Like, if you run `./linux-wallpaperengine $ID` (where $ID is the ID of an installed wallpaper from Wallpaper Engine).
