### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bucks9052** [Almamu/linux-wallpaperengine#19]
**Describe the bug**

**To Reproduce**
1. Go to step 5.3 
2. type cmake ..
3. Scroll down to the error
4. it says CMake Error: The source directory "/home/someone" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Expected behavior**
It should build

**(please complete the following information):**
 - OS: Linux mint 19
 - X11 server Version: latest
 - Window manager: not sure
 - Version not sure

**Comment by ambidot** [comment]
Are you running `cmake ..` in a build directory? It should refer to the source directory as `/home/someone/linux-wallpaperengine-master` or similar. If you want to build in the source directory you can use `cmake .`

**Comment by Almamu** [comment]
Issue seems solved, the user has opened a new one: #21
