### ISSUE TITLE
[BGFIX] 2583081521

### ISSUE THREAD

**Issue by Weather-OS** [Almamu/linux-wallpaperengine#191]
**Wallpaper Engine Background(s)**

[Link(s) to the background(s) in the steam workshop or their background ID(s).](https://steamcommunity.com/sharedfiles/filedetails/?id=2583081521)

**Console output**

[output.txt](https://github.com/Almamu/linux-wallpaperengine/files/13566415/output.txt)

**Desktop (please complete the following information):**
 
- OS: Arch Linux
 - Desktop Environment: GNOME 45
 - Window Manager: mutter

**Additional context**

I'm using Xorg. I have 2 Discrete GPUs. An NVIDIA RTX 3060 and an AMD Radeon RX 5600 XT that drives my main displays.

Launching this background just results in a gray screen. That's it.
It does say that it cannot setup images which is weird.
This wallpaper did work with linux-wallpaper engine at some point in the past as I've tried it before. But at some other point, it stopped functioning.

**Comment by Almamu** [comment]
There were some changes to how backgrounds work and the app needs some updating until the compatibility goes back to where it was. I made some commits yesterday that might improve compatibility, but It still needs some work. I'll add this background to the list of things to look into

**Comment by Almamu** [comment]
Background should at least display something now. Particles are not supported yet, so the background just displays a static image,  but that's already tracked in it's own issue #52, so I'll be closing this one.
