### ISSUE TITLE
[BGFIX] 1845706469(Example from Readme.md) shows a grey screen with latest WallPaper engine

### ISSUE THREAD

**Issue by JustSimplyKyle** [Almamu/linux-wallpaperengine#198]
**Wallpaper Engine Background(s)**

1845706469

**Console output**

Previous Release stdout :https://c-v.sh/forcelesschaptrels.txt
Current Release stdout:  https://c-v.sh/jugateploddings.txt

**Screenshots**

Last Previous Release:
![image](https://github.com/Almamu/linux-wallpaperengine/assets/68589851/a410d800-97d6-4925-8191-23a65f4a5a61)
Current Release:
Grey screen.

**Desktop (please complete the following information):**
 
- OS: Arch Linux
 - Window Manager: Hyprland

**Additional context**

Any additional information about your setup

**Comment by Almamu** [comment]
I've just tried the background on sway + wlroots and seems to work just fine, maybe something changed between your test and mine? Please re-open the issue if the issue still persist, logs don't really show anything wrong hapening
