### ISSUE TITLE
wp::video::node::render() is empty?

### ISSUE THREAD

**Issue by lhy0403** [Almamu/linux-wallpaperengine#2]
The program gives me a solid black output, even after I modified the path to WallPaper Engine Projects folder, I see the `render()` method is empty, what does it (or at least should) do?

**Comment by Almamu** [comment]
wp::video::node is the base class for all the different types of nodes the scene can have. right now only the materials are implemented, so if your scene uses models, web-browser or video the content won't be displayed (in fact you should be seeing an error in the log).

As I haven't implemented the Wallpaper engine texture format yet only PNG/JPG textures are supported. #1 
Right now this is as far as you can get with any background: https://imgur.com/qJkzJ4g
This is the background I'm loading in that picture: https://drive.google.com/file/d/1rs-tiJ3uQPHC869-GbiUwpc0r1RcJfev/view?usp=sharing

You'll notice that for every material, there is a png or jpg file with the actual texture.

Shaders support is implemented but they aren't loaded yet from the project.json file as I still have to implement the parser for them.

**Comment by lhy0403** [comment]
Okay, finally I tried the scene you provided and it works fine, but it's weird that I didn't receive any error message when I was using the *default scenes of Wallpaper Engine (like that car, and some DNA structure thing)*.

**Comment by Almamu** [comment]
Thank you for the heads up, hopefully I'll be able to start testing with other wallpapers soon so I can fix more bugs and implement things like the the decompress routine for final backgrounds downloaded from the steam store.
