### ISSUE TITLE
XDG APP ID not set

### ISSUE THREAD

**Issue by WinteruOfficiel** [Almamu/linux-wallpaperengine#202]
I'm trying to use this app with hyprland (using  hyprwinwrap) but that doesn't work because the app isn't setting the XDG APP ID variable.

**Comment by Almamu** [comment]
I don't use Hyprland so I cannot test, but have you tried using the --screen-root command-line switch? Support for wayland should be working, right now I'm using wlroots and have multiple backgrounds without issues on my end.

**Comment by WinteruOfficiel** [comment]
I'm sorry, I misread the documentation. It looked like hyprland couldn't do that without hyprwinwrap which required the class name of the window. It actually works. 

Though, I'm not really aware of all the wayland protocol but it looked like this variable was recommended to be set but it's not a big deal I think.

Thank you for this amazing software, I love wallpaper engine.
