### ISSUE TITLE
[BGFIX]

### ISSUE THREAD

**Issue by nosko-stojachkov** [Almamu/linux-wallpaperengine#203]
**Wallpaper Engine Background(s)**
https://steamcommunity.com/sharedfiles/filedetails/?id=2282120494

**Console output**

[terminal.txt](https://github.com/Almamu/linux-wallpaperengine/files/14396409/terminal.txt)

**Screenshots**

If you have any screenshot of it working on Windows that'll help so we can compare both outputs

**Desktop (please complete the following information):**
 
- OS: [Fedora Linux 39 ]
 - Desktop Environment: [GNOME 45.4]
 - Window Manager: [X11]

**Additional context**

**Comment by Almamu** [comment]
The background seems to load and display somewhat properly (I guess it's missing particle effects, but that's out of scope for now) so I'll be closing the issue, feel free to re-open it with more details.
