### ISSUE TITLE
Help with xrandr

### ISSUE THREAD

**Issue by bucks9052** [Almamu/linux-wallpaperengine#21]
**Describe the bug**
It says i am missing Xrandr but when i type it lowercase in terminal it works just fine any help?

**To Reproduce**
1. Go to the directory run cmake .
2. Scroll down to the error
3. See error

**Expected behavior**
it should run cmake

**Screenshots**
![image](https://user-images.githubusercontent.com/56772450/87453372-66653680-c5d0-11ea-92fb-f7f434a7e798.png)

**(please complete the following information):**
 - OS: mint 19
 - X11 server Version: latest
 - Window manager: not sure
 - Version not sure

**Comment by Almamu** [comment]
You are missing the xrandr library, not the command-line tool. Install the ```libxrandr``` package and that should get rid of the error.

**Comment by Almamu** [comment]
No answer on this, I'll close it. Feel free to re-open If you haven't solved it yet

**Comment by bucks9052** [comment]
![image](https://user-images.githubusercontent.com/56772450/88702304-25dde080-d0d9-11ea-8e46-c4491e3a21ad.png)
I installed the lib but it seems to still not work

**Comment by bucks9052** [comment]
![image](https://user-images.githubusercontent.com/56772450/88702592-84a35a00-d0d9-11ea-92ab-ae499e23d724.png)

**Comment by Almamu** [comment]
What cmake version are you using? (you can obtain this with ```cmake --version```).

As a temporal fix, please try to remove the line 6 of CMakeLists.txt and try again, that might be interfering with the normal detection of cmake (although It seems to work on other systems without issue).

**Comment by bucks9052** [comment]
im on cmake 3.10.2 and when i removed that line it still did not work

**Comment by bucks9052** [comment]
what should i try next?

**Comment by Almamu** [comment]
To be honest, I'm kind of lost. Can you try creating a build folder and running cmake there? (undoing the changes to the CMakeFiles.txt file)
```
mkdir build
cd build
cmake ..
make
```
