### ISSUE TITLE
video wallpaper does not work on wayland

### ISSUE THREAD

**Issue by saying121** [Almamu/linux-wallpaperengine#211]
The video wallpaper will show in window

WM: hyprland

run:
```bash
linux-wallpaperengine 1087925015 --screen-root eDP-1
```

![image](https://github.com/Almamu/linux-wallpaperengine/assets/74663483/b6b49536-f105-48aa-8278-e37e7019d1f2)

**Comment by Almamu** [comment]
I'm investigating this one as there seems to be something funky going on between mpv and wayland.

**Comment by Almamu** [comment]
Looks like mpv made some breaking changes that required of some changes on the implementation to work. https://github.com/mpv-player/mpv/discussions/13974

A fix should be already up in the repo. Please let me know if any issue arises.
