### ISSUE TITLE
[BGFIX] Wallpapers do not load when binary is called from another directory

### ISSUE THREAD

**Issue by learnedtim** [Almamu/linux-wallpaperengine#223]
**Wallpaper Engine Background(s)**

https://steamcommunity.com/sharedfiles/filedetails/?id=3208739106

**Console output**

$ /home/kai/scripts/wallpaper/build/wallpaperengine /home/kai/.local/share/Steam/steamapps/workshop/content/431960/3208739106  --screen-root eDP-1 --fps 60
[0601/190340.223760:ERROR:icu_util.cc(240)] Invalid file descriptor to ICU data received.
Trace/breakpoint trap (core dumped)

**Desktop (please complete the following information):**
 
- Arch Linux
 - Wayland
 - Hyprland

**Additional context**

The wallpaper runs fine when the linux-wallpaperengine executable is ran in the same directory; otherwhise it creates a core dump. When trying to make the wallpaper start on WM start, the WM being Hyprland, it crashes aswell.

**Comment by Gustash** [comment]
@Almamu there's something wrong with how the binary is looking for libcef.so

#216 is related to this

**Comment by Almamu** [comment]
If you're using the Arch's AUR package update it. After adding support for web wallpapers it needed some adjusting for it to properly install and run.

**Comment by checkinindza** [comment]
Seems like it still happens as I encounter the same issue aswell, same setup. I cloned the repo, haven't installed a package.
