### ISSUE TITLE
I can not use it. libcef.so

### ISSUE THREAD

**Issue by odinhaknet** [Almamu/linux-wallpaperengine#224]
I can not use it

I have installed the package from AUR but when executing I get this error:

`linux-wallpaperengine: error while loading shared libraries: libcef.so: cannot open shared object file: No such file or directory`

And there is no `libcef ` in AUR or pacman.

**Comment by Almamu** [comment]
Should be fixed with the latest version of the package in the AUR. Please re-open if the issue persists.
