### ISSUE TITLE
Opens a window with the wallpaper instead of applying it

### ISSUE THREAD

**Issue by Damglador** [Almamu/linux-wallpaperengine#237]
System:
![зображення](https://github.com/user-attachments/assets/8e02b49f-1439-4521-a56b-8b29d052d151) (yes, I use Arch BTW)
![зображення](https://github.com/user-attachments/assets/231bb3cd-9456-4335-b4c9-1d4e9888ee33)
Tried AUR package first and then with self-compiled version

**Comment by Inmoresentum** [comment]
Please read the [README.md](https://github.com/Almamu/linux-wallpaperengine?tab=readme-ov-file#553-running-as-a-screens-background) :). Alternatively, I have noticed that you are on KDE Plasma. Hence, you can use [wallpaper-engine-kde-plugin](https://github.com/catsout/wallpaper-engine-kde-plugin) which should be more user friendly for you.
