### ISSUE TITLE
[BUG] Do not work from the store

### ISSUE THREAD

**Issue by GoogeTan** [Almamu/linux-wallpaperengine#24]
Don't run wallpapers from the store, but only those that you made yourself.
Error in logs:
`Irrlicht Engine version 1.8.4
Linux 5.6.19-2-MANJARO #1 SMP PREEMPT Wed Jun 17 22:24:52 UTC 2020 x86_64
Using renderer: OpenGL 4.3
NV134: nouveau
OpenGL driver version is 1.2 or better.
GLSL version: 4.3
terminate called after throwing an instance of 'nlohmann::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at 1: syntax error - unexpected end of input; expected '[', '{', or a literal
Aborted (core dumped)
`
Also, even my wallpapers are not shown on the desktop If I don't use --screen-root DVI-D-1 it opens in a window, but if I use it it doesn't open at all.
 - OS: Arch Linux Monjaro

**Comment by GoogeTan** [comment]
sorry for such a short description

**Comment by Almamu** [comment]
What wallpaper are you trying to run? 

The application will run in a window unless you specify the screen you want it to run in, this is to ease the testing for the time being (as It's still in the early stages), please take in mind that compositors usually take control over the root window and will draw over the wallpaper, so support for those has to be added manually first.

**Comment by GoogeTan** [comment]
For example: 
[asuka.zip](https://github.com/Almamu/linux-wallpaperengine/files/4996149/asuka.zip)
It works in windows, but in linux not.

**Comment by UltraBlackLinux** [comment]
Same error here, thats my command: 
`./wallengine --screen-root HDMI-A-0s --screen-root DVI-D-0 --pkg /home/maus/.local/share/Steam/steamapps/workshop/content/431960/2201621201/`

**Comment by Almamu** [comment]
Seems to be a matter of adding the package version to the list of supported versions. @GoogeTan yours was fixed on one of these two commits: 82e92baae804aaa3694326ae471f5755146644eb  or 39d3f4f1e096d0600ee088ca24f52bff149ae62f

@UltraBlackLinux your crash is the same exact issue, but this one is fixed on the last commits on data-separation and master branches (b1dd837cca71b0f34c49b64b0bd1c870919bc7aa and d5817deb980e7ecc65f5f71a0640a4e6562da8bc for master and d5ee71540d9225d85b48a8fde35ba4d7e7cf97a5 for data-separation)
