### ISSUE TITLE
Wrong CPU arch guess by CMake

### ISSUE THREAD

**Issue by im-vmn** [Almamu/linux-wallpaperengine#265]
cmake decided that my cpu arch is amd64 (I use aarch64) and tried to download cef (amd64 version), cmake configuration prints no errors, the compilation failed with:

**c++: error: unrecognized command-line option ‘-m64’**

**My system:**

CPU - Rockchip 3588 (OrangePi 5), aarch64
OS - Ubuntu 24.04 (Linux 6.1.0-1025-rockchip)
DE - GNOME on Wayland

**Steps:**

1. Install dependencies with the command from README (libmpv1 was not found, it was libmpv2 in my case)
2. Clone repository
3. Follow instructions from the README

**Workaround:**

Remove lines 42-72 from CMakeLists.txt and explicitly do:

1. set(CEF_PLATFORM "linuxarm64")
2. set(PROJECT_ARCH "arm64")

After this correct CEF build was downloaded and compilation instructions were generated correctly. But this breaks automatic system guess. Wouldn't it be better to check arch under linux with **uname -p** or **lscpu | head -n 1**?

**Comment by Almamu** [comment]
Under the hood ```CMAKE_SYSTEM_PROCESSOR``` should call uname -m, it could be that this specific arch is not taken into account. I've pushed 458605c218c736a76a4ac3a3ddefb82db02f0aab and dc1d40e8cf0aa3e2780cff9624a9cd5f953aa671 to output in the cmake log what arch it detected (and why) so we can add your arch to the checks so it downloads the proper version. Please run cmake again and copy the output here. There should be a message similar to 
```
-- Using CEF for Linux - linux64 (Based on void size 8 (x86_64))
```

**Comment by im-vmn** [comment]
I pulled these changes and tried to run cmake again, here is the output:


```
-- Using CEF for Linux - linux64 (Based on void size 8 (aarch64))
CMake Error at CMakeModules/FindCEF.cmake:33 (message):
  No CMake bootstrap found for CEF binary distribution at:
  /home/utils/linux-wallpaperengine/third_party/cef/cef_binary_120.1.10+g3ce3184+chromium-120.0.6099.129_linux64.
Call Stack (most recent call first):
  CMakeLists.txt:87 (find_package)
```

**Comment by Almamu** [comment]
I've added your arch to the list of detected archs in the CMakeLists.txt and should work now, please reopen the issue if it persist.
