### ISSUE TITLE
Issue when preforming make command

### ISSUE THREAD

**Issue by darkaquapc** [Almamu/linux-wallpaperengine#266]
When trying to make the Executable i am receiving this error.

[ 63%] Built target libcef_dll_wrapper
[ 63%] Building CXX object CMakeFiles/linux-wallpaperengine.dir/main.cpp.o
In file included from /home/mpigman/Downloads/New Folder/main.cpp:4:
/home/mpigman/Downloads/New Folder/src/WallpaperEngine/Application/CApplicationContext.h:8:10: fatal error: glm/vec4.hpp: No such file or directory
    8 | #include <glm/vec4.hpp>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/linux-wallpaperengine.dir/build.make:76: CMakeFiles/linux-wallpaperengine.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/linux-wallpaperengine.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by im-vmn** [comment]
"**Something**: No such file or directory" means that you don't have a library that provides this file. If you use apt try this:

sudo apt install libglm-dev

**Comment by darkaquapc** [comment]
Thank You
