### ISSUE TITLE
[BUG] Wallpaper does not apply

### ISSUE THREAD

**Issue by UltraBlackLinux** [Almamu/linux-wallpaperengine#28]
**Describe the bug**

**To Reproduce**
`./wallengine --screen-root HDMI-A-0 --screen-root DVI-D-0 --pkg /home/maus/.wallpaperengine/steam wallpapers/1461427298/`:
[1461427298.zip](https://github.com/Almamu/linux-wallpaperengine/files/5122587/1461427298.zip)
```
Found requested screen: HDMI-A-0 -> 0x75:1680x1050
Found requested screen: DVI-D-0 -> 1680x0:1920x1200
Irrlicht Engine version 1.8.4
Linux 5.8.1-3-MANJARO #1 SMP PREEMPT Sat Aug 15 19:17:30 UTC 2020 x86_64
Using renderer: OpenGL 4.6
Radeon RX 560 Series (POLARIS11, DRM 3.38.0, 5.8.1-3-MANJARO, LLVM 10.0.1): X.Org
OpenGL driver version is 1.2 or better.
GLSL version: 4.6
Could not create archive for: /home/maus/.wallpaperengine/steamscene.pkg
terminate called after throwing an instance of 'nlohmann::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at 1: syntax error - unexpected end of input; expected '[', '{', or a literal
Abgebrochen (Speicherabzug geschrieben)
```

`./wallengine --screen-root HDMI-A-0 --screen-root DVI-D-0 --pkg /home/maus/.local/share/Steam/steamapps/workshop/content/431960/2186698820/`:
[2186698820.zip](https://github.com/Almamu/linux-wallpaperengine/files/5122580/2186698820.zip)
```
Found requested screen: HDMI-A-0 -> 0x75:1680x1050
Found requested screen: DVI-D-0 -> 1680x0:1920x1200
Irrlicht Engine version 1.8.4
Linux 5.8.1-3-MANJARO #1 SMP PREEMPT Sat Aug 15 19:17:30 UTC 2020 x86_64
Using renderer: OpenGL 4.6
Radeon RX 560 Series (POLARIS11, DRM 3.38.0, 5.8.1-3-MANJARO, LLVM 10.0.1): X.Org
OpenGL driver version is 1.2 or better.
GLSL version: 4.6
LOAD TEX: This is an ARGB8: materials/particle/halo_2.tex
Loaded texture: materials/particle/halo_2.tex
LOAD TEX: This is an ARGB8: materials/masks/pulse_mask_ee0d9bbc6d0516b8583c8fb3e841485c0b7ec4e8.tex
Loaded texture: materials/masks/pulse_mask_ee0d9bbc6d0516b8583c8fb3e841485c0b7ec4e8.tex
ERROR PRE-COMPILING SHADER
racter
GLSL shader failed to compile
0:1(1): error: syntax error, unexpected end of file

LOAD TEX: This is an ARGB8: materials/particle/halo_5.tex
Loaded texture: materials/particle/halo_5.tex
LOAD TEX: This is an ARGB8: materials/masks/pulse_mask_681d95af21112ea41fc4cd51aa49d9c553ef1173.tex
Loaded texture: materials/masks/pulse_mask_681d95af21112ea41fc4cd51aa49d9c553ef1173.tex
ERROR PRE-COMPILING SHADER
racter
GLSL shader failed to compile
0:1(1): error: syntax error, unexpected end of file

LOAD TEX: Unknown texture format
: materials/particle/beam/beam_2_fade.tex
Could not load texture: materials/particle/beam/beam_2_fade.tex
LOAD TEX: This is an ARGB8: materials/masks/pulse_mask_14baecd88cd86197979e9592a3614e57bbd01235.tex
Loaded texture: materials/masks/pulse_mask_14baecd88cd86197979e9592a3614e57bbd01235.tex
ERROR PRE-COMPILING SHADER
racter
GLSL shader failed to compile
0:1(1): error: syntax error, unexpected end of file

LOAD TEX: This is an ARGB8: materials/masks/shake_mask_5207177ba9b3baf118953fd6a547ac67ade9efd7.tex
Loaded texture: materials/masks/shake_mask_5207177ba9b3baf118953fd6a547ac67ade9efd7.tex
LOAD TEX: Skipping broken mask: materials/util/white.tex
Loaded texture: materials/util/white.tex
LOAD TEX: This is an ARGB8: materials/masks/shake_mask_fa9c74bb537d37334f47fa1231eb92d0e2c956cc.tex
Loaded texture: materials/masks/shake_mask_fa9c74bb537d37334f47fa1231eb92d0e2c956cc.tex
ERROR PRE-COMPILING SHADER
racter
GLSL shader failed to compile
0:1(1): error: syntax error, unexpected end of file

LOAD TEX: This is a JPG: materials/minimalistic landscape 2.tex
Loaded texture: materials/minimalistic landscape 2.tex
LOAD TEX: This is an ARGB8: materials/workshop/2127844565/bar.tex
Loaded texture: materials/workshop/2127844565/bar.tex
```

**Expected behavior**
It should apply the wallpaper, but it doesnt. The recent fixes regarding this problem didnt seem to really fix anything, sadly.

**(please complete the following information):**
   - OS: Manjaro
   - X11 server Version: 1.20.8
   - Window manager: kde
   - Version 20.04.3

**Comment by Almamu** [comment]
These are different issues that the ones mentioned on #24 

The path to the pkg file is not correct. Make sure you escape all the spaces and/or special characters, the command should be this:
```
 ./wallengine --screen-root HDMI-A-0 --screen-root DVI-D-0 --pkg /home/maus/.wallpaperengine/steam\ wallpapers/1461427298/
```
The first background loads properly for me on the master branch, but I did have to make some changes to data-separation for it to load properly, seems to be an old version of the file format that didn't have required data.

The second background seems to be too complex for the master branch (which only loads simple backgrounds), it works on the data separation (well, kind of), but things like the text are not supported yet.

**Comment by UltraBlackLinux** [comment]
oh lol I didnt even notice the space - I recently created the shortcut xD
Thanks again!

**Comment by UltraBlackLinux** [comment]
oof. now the sound plays, but the wallpaper isnt applied - huh?

**Comment by UltraBlackLinux** [comment]
@Almamu ?

**Comment by UltraBlackLinux** [comment]
When entering no screen, a window opens:
![Screenshot_20200830_163907](https://user-images.githubusercontent.com/62404294/91661929-65845780-eadf-11ea-9f49-e47fce855474.png)
When entering one, nothing happens.

**Comment by Almamu** [comment]
This is the exact same issue as #8 mentions, your desktop environment is drawing to the root window so wallpaper engine cannot draw to it too, but if you run it in window mode (as it's running if you don't specify a screen) the wallpaper will display properly. There's no current fix for that as this requires special code to handle different desktop environments.
