### ISSUE TITLE
Porting to Android

### ISSUE THREAD

**Issue by KarkaLT** [Almamu/linux-wallpaperengine#32]
Is there a possibility to port this engine to Android?

**Comment by UltraBlackLinux** [comment]
I wouldnt want to do this. Would suck up too many resources...

**Comment by Almamu** [comment]
To be honest, I have no idea if that would be possible. It seems to be possible to compile irrlicht for Android, so I guess it'd work, but I sincerely doubt it'll be fast and low-power enough for it to be worth it running on the phone... Not to mention the platform-specific code required to make the app the actual background (for which I have no clue at all).

All in all, that's waaaay out of the scope of the project anyway, so even If it was possible at all, It would not be a priority. Right now the work is slow and there's greater priorities like getting better support for backgrounds on the data-separation branch so we can finally start working on particles, and eventually, on 3D models support.
