### ISSUE TITLE
[BUG] Could not create archive for: assets.zip

### ISSUE THREAD

**Issue by RandomIssues** [Almamu/linux-wallpaperengine#34]
**Describe the bug**
When i try to run wallengine (compressed or uncompressed), i get an error "Could not create archive for: assets.zip"

**To Reproduce**
1. Run a command like "./wallengine --dir /home/anidiot/Wall/921617616/"
2. See Error

**Expected behavior**
Just create the archive and behave like it should

**Screenshots**
anidiot@alaptop:~/linux-wallpaperengine$ make
[  4%] Linking CXX executable wallengine
[100%] Built target wallengine
anidiot@alaptop:~/linux-wallpaperengine$ ./wallengine --dir /home/anidiot/Wall/921617616/
Irrlicht Engine version 1.8.4
Linux 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64
Using renderer: OpenGL 4.6.0
GeForce 920M/PCIe/SSE2: NVIDIA Corporation
OpenGL driver version is 1.2 or better.
GLSL version: 4.6
Could not create archive for: assets.zip
Cannot initialize SDL audio system: Mixer not built with MP3 support (figured about the issue)
anidiot@alaptop:~/linux-wallpaperengine$ 

**(please complete the following information):**
 - OS: [Ubuntu 20.04.1 LTS (may try debian if asked)]
 - X11 server Version: [X.Org version: 1.20.8]
 - Window manager: [GNOME Shell]
 - Version [GNOME Shell 3.36.4]

**Additional context**
Just build it parsing dependencies using help from google.

**Comment by Almamu** [comment]
Please check the how to use guide on the README.md of the repository: https://github.com/Almamu/linux-wallpaperengine#5-how-to-use
You'll need to extract the default assets from wallpaperengine following the guide in order for it to run. Please take in mind that the software is in it's early stages, so there's a big chance your background won't display properly. 

You might also want to test the data-separation branch which includes better support for the engine (but there's some rendering issues pending to be fixed).

**Comment by RandomIssues** [comment]
Sorry, i forgot to follow a step and i havn't double checked it before opening an issue, thanks.

I have an other issue i will try to investigate (and maybe open another issue) but thanks for telling me there is another branch (so i will test it).

Thanks
