### ISSUE TITLE
Installation issue (CMake Compiler not set)

### ISSUE THREAD

**Issue by Zracoh** [Almamu/linux-wallpaperengine#35]
cmake ..
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/home/et/Téléchargements/wallpaper engine/build/CMakeFiles/CMakeOutput.log".

CMakeOutput.log =
The system is: Linux - 5.6.19-159.current - x86_64

Aaaand.. That's it. Any workaround ?

**Comment by Almamu** [comment]
You're missing the C++ compiler. If you're running debian/ubuntu you can install those (and some extra dev tools like gdb) with the following command:
```
apt install build-essential
```

On CentOS/Fedora you can do the same this way:
```
yum groupinstall "Development Tools"
```

**Comment by Zracoh** [comment]
Done !

For anyone using Solus : 
```
sudo eopkg it -c system.devel
sudo eopkg it -c libx11-devel
```

and so on !

Problem solved !
