### ISSUE TITLE
not able to install

### ISSUE THREAD

**Issue by giovuddu** [Almamu/linux-wallpaperengine#37]
i cannot understand how to use cmake and what to do,i think the problem is that in ubuntu instead of x11 and xrandr, i have x11-xserver-utils, can i use this program whith that? if so can I have some help for the installation?

**Comment by Almamu** [comment]
Hey! Sorry for the late answer, you should be able to compile the project following the steps on the readme here: https://github.com/Almamu/linux-wallpaperengine#53-compilation-steps

For x11 and xrandr, I'm talking about the development libraries of those, for the xrandr package you'll need to install ```libxrandr-dev``` and for x11 you'll need ```libx11-dev```. Please let me know if you have any other issues/questions ;)
