### ISSUE TITLE
[BUG] terminate called after throwing an instance of 'nlohmann::detail::type_error'

### ISSUE THREAD

**Issue by Vladsg** [Almamu/linux-wallpaperengine#39]
![изображение](https://user-images.githubusercontent.com/19352528/123491390-39623600-d61f-11eb-9200-163f022094bf.png)
Cant run any wallpaper. Tried many times (about 15 wallpaper)
(Wallpaper example: [link](https://steamcommunity.com/sharedfiles/filedetails/?id=1165486336) )

**Comment by Lin2D2** [comment]
I have the same Problem, found some that work, but then there is another error. The error is from include/nlohmann/detail/connversions/from_json.hpp

**Comment by Almamu** [comment]
Sorry, I did not see this issue when It was opened. This usually happens because I made assumptions about what the background data is. @Lin2D2 can you share the background you're using? I'm going to bed now, but I can do some testing tomorrow.
