### ISSUE TITLE
I Follow The Compilation Steps but ./wallengine Never Gets Made

### ISSUE THREAD

**Issue by ChadGaming** [Almamu/linux-wallpaperengine#40]
**Describe the bug**
Doesnt Produce wallengine File When Compiling, Rendering the project useless
Ive been at this for a week lol, cant figure it out :/

**To Reproduce**
1. Make Build dir (in home dir)
2. Extract Files from /linux-wallpaperengine-master/ to build dir
3. move assets.zip to build dir
4. cmake ..
5. Term Output
6. 
7. {
7. CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/bingus/build

8. } (hehe bingus lol)
9.
10.(in term) make
11.output is nothing
bingus@bingus-Aspire-ES1-512:~/build$ make (i dont know why when previewing its crossed it out :| )
bingus@bingus-Aspire-ES1-512:~/build$           (same here)

12. i looked into Cmakelists.txt and its should produce wallengine but, it makes everything but that.
13. Build, Terminal and Scene Screenshot
![Screenshot_20210712_063824](https://user-images.githubusercontent.com/86333753/125274353-e3a6b280-e2db-11eb-98b2-9bd2716c6210.png)

Here is a Zip of My Entire Build Dir
https://mega.nz/file/hHxXGQxD#5sYcE2RZtGCPoNvnpG8LzfHuAT75AaS7IXQPkZ9Hrzs

**Expected behavior**
Produce a "wallengine" File in Build Dir

**(please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS x86_64 

Sorry if im Stupid and this is actually working. but i cant seem the figure it out.

**Comment by ChadGaming** [comment]
Also, I forgot I labelled it as a bug so sorry if that wrong :/

**Comment by Almamu** [comment]
You are doing cmake .. to your user folder (which I guess does not have any CMake project files). The build folder has to be created inside the root directory of the project, so if you cloned linux-wallpaperengine to /home/user/wallpaperengine, your build folder should be in /home/user/wallpaperengine/build. Then you can run ```cmake ..``` from that build folder. CMake output will be longer.

**Comment by ChadGaming** [comment]
Ill try that, ill reply again if it works. But right now gotta charge my laptop lol

**Comment by ChadGaming** [comment]
it worked thanks for the help
