### ISSUE TITLE
[Installation issues] Undefined reference to symbol in libIrrlicht

### ISSUE THREAD

**Issue by Muxed0** [Almamu/linux-wallpaperengine#41]
After following the installation instructions and installing the requisite libraries (I had to install so many versions of SDL for the cmake to leave me alone), I can finally run make. Everything goes smoothly and then the linking process gets aborted as soon as it starts, spitting out:
```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libIrrlicht.a(CIrrDeviceLinux.o): undefined reference to symbol 'XF86VidModeGetGamma'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libXxf86vm.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/wallengine.dir/build.make:386: wallengine] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/wallengine.dir/all] Error 2

```
I scoured the net for a bit and found two possible causes:
1- missing libraries (namely /usr/lib/x86_64-linux-gnu/libX11.so and /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 which are both present)
2- error in the makefile or compiler command which I don't want to mess with

For me, reproducing is simple. Just try to run make, it won't work.

I expected it to install correctly after following the installation instructions but no such luck.

I am using:
 - OS: Pop! OS 20.04
 - X11 server Version: 1.20.9
 - Window manager: mutter (gnome DE)
 - Version: most recent

Note that one part where I may  have screwed up is how I installed Irrlicht. I downloaded the source code, followed the instructions to make the binary library and moved it and the includes in the respective directories on the system. Still, considering I can compile and run the Irrlicht examples fine, I feel like I should have done a decent job.

**Comment by Almamu** [comment]
These irrlicht linking issues should be fixed on the latest version of the main branch as Irrlicht is not a requirement anymore. If you still have issues building the project, please open a new issue.
