### ISSUE TITLE
Install on fedora 34

### ISSUE THREAD

**Issue by Ajegon24** [Almamu/linux-wallpaperengine#42]
I cant manage to install this on Fedora 34. When i run the "cmake .." command i get the following output:

-- Checking for module 'xrandr'
--   Package 'xrandr', required by 'virtual:world', not found
CMake Warning (dev) at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (XRANDR)
  does not match the name of the calling package (Xrandr).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  CMakeModules/FindXrandr.cmake:64 (find_package_handle_standard_args)
  CMakeLists.txt:10 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find GLUT (missing: GLUT_glut_LIBRARY GLUT_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindGLUT.cmake:139 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:12 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/Ajegon/.linux-wallpaperengine/build/CMakeFiles/CMakeOutput.log".
See also "/home/Ajegon/.linux-wallpaperengine/build/CMakeFiles/CMakeError.log".

I checked wether xrandr  was installed, it sure is. Any clue on what the issue could be?

**Comment by Almamu** [comment]
Sorry for the late reply, have you installed the libxrandr-devel? xrandr has two packages, one is the binary and the other is required for the compilation. Also, you might want to check the issue #16 as It covers issues you might find when compiling on Fedora.

**Comment by Almamu** [comment]
I'll close this one for now as there's been no answer and I cannot test on Fedora for now (and other users didn't seem to have any issue with it).

**Comment by black-roland** [comment]
Please try `dnf install /usr/lib/libglut.so`. This command will install `freeglut` and `freeglut-devel`.

**Comment by black-roland** [comment]
Please try `dnf install freeglut freeglut-devel` on Fedora.
