### ISSUE TITLE
ERROR PRE-COMPILING SHADER

### ISSUE THREAD

**Issue by monkhaze** [Almamu/linux-wallpaperengine#44]
Hi,

I've managed to build the project and I can run video based wallpapers just fine but can't seem to get any shader based ones to work.

I've tried:
https://steamcommunity.com/sharedfiles/filedetails/?id=1845706469&insideModal=0&requirelogin=1 (Which seems to be the one that should work according to github docs)
https://steamcommunity.com/sharedfiles/filedetails/?id=1281527981

Everything seems to give me the following error:
terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR PRE-COMPILING SHADER
zsh: abort (core dumped)  ./wallengine --pkg 1281527981

Currently using GTX 1060 with Nvidia proprietary driver.

**Comment by Almamu** [comment]
Hi @monkhaze that's actually not the background that I've been using for testing. The one I have doesn't have background music and is a bit brighter than that one and has less effects. (I'd link it but I cannot find any link to it anymore, I found it on Nier Automata's subreddit some time ago). And It's also using some advanced features that are not fully supported yet, It should be supported some time in the future, but I first need to understand exactly how some of those features work.

The second background you linked should work just fine. I've just uploaded some fixes to proportions so the backgrounds fit on your screen if the background is too big for it, but I have not had any issues with 1281527981

**Comment by Almamu** [comment]
With the latest fixes uploaded to main, both backgrounds should work properly (being particles the only thing that lacks support, being tracked on #52). Please re-open the issue if any of these do not work (or you find other backgrounds that do not display properly so I can add them to my testing lists).
