### ISSUE TITLE
Add support for sound in backgrounds

### ISSUE THREAD

**Issue by Almamu** [Almamu/linux-wallpaperengine#5]
As simple as that, support sound playback on backgrounds that have it. This one serves as a good start: https://steamcommunity.com/sharedfiles/filedetails/?id=1388021819

**Comment by KaitoCross** [comment]
Also please add a feature to disable wallpaper sounds in general!

**Comment by Almamu** [comment]
Sound should be implemented with 7410f238ac0ac94da11d3af2ac0dfaae1b93f3f6
Added the option --silent to mute all the sound.
