### ISSUE TITLE
FreeImage missing on compilation step

### ISSUE THREAD

**Issue by Almamu** [Almamu/linux-wallpaperengine#50]
I clone glfw repo to lib/glfw and cmake work, but when i build with make, its finished with error
![изображение](https://user-images.githubusercontent.com/19352528/132754965-39eefafe-9c10-48c8-beef-c1e39e984c6f.png)
FreeImage installed

_Originally posted by @Vladsg in https://github.com/Almamu/linux-wallpaperengine/issues/49#issuecomment-916398665_

**Comment by Almamu** [comment]
@Vladsg can you please run cmake again on an empty build folder and look at the output? You should see something like
```
Found FreeImage: headers at /usr/include, libraries at  :: /usr/lib/libfreeimage.so
```

**Comment by Vladsg** [comment]
![изображение](https://user-images.githubusercontent.com/19352528/132756505-0b5805fa-b4e4-47ac-9d22-d3cc87a62693.png)
but without glfw repo cmake not successful

**Comment by Vladsg** [comment]
ok my mistake, i recreate repo clone, but not clone gflw repo/ I clone and start make again and it successful

**Comment by Almamu** [comment]
Okay, I'll close the issue then.
