### ISSUE TITLE
Wayland support?

### ISSUE THREAD

**Issue by Toorero** [Almamu/linux-wallpaperengine#53]
Is there any way linux-wallpaperengine can support Wayland?

**Comment by Almamu** [comment]
I'm not really familiar with Wayland or how it works, so I cannot really say anything for sure on Wayland support. Right now the main focus is to get backgrounds to properly load instead of missing effects and particles, so support for other servers is a bit out of the scope for now.

**Comment by yavko** [comment]
I've never used x11 and won't ever, I like to stick to bleeding edge things. Anyways a Wayland version would be great I would try to help on a Wayland version except I have zero experience with c++.

**Comment by UltraBlackLinux** [comment]
It does work for me. I assume it's running on XWayland

**Comment by eternal-sorrow** [comment]
layer-shell version for wlroots compositors would be great

**Comment by UltraBlackLinux** [comment]
did work in-house when I last tried it like a month ago.

**Comment by ccptr** [comment]
I can confirm that it works on Hyprland. :)
