### ISSUE TITLE
error on make (Linking CXX executable wallengine)

### ISSUE THREAD

**Issue by nYCSTs** [Almamu/linux-wallpaperengine#63]
![wall_engine_err](https://user-images.githubusercontent.com/63932475/145498190-124c9ad2-4475-4671-bcf1-08d3c13159e8.png)

I'm using Debian 10

**Comment by Almamu** [comment]
Looks like the linker cannot find the definitions for the std::filesystem::filesystem_error class that is used to report some of the problems when loading the background information. This is part of the C++17 specification. Maybe you're missing some libraries? On debian 10 a good point to start compiling things is to make sure you install the build-essential package. Other than that, I'm not really sure what might be going on here.

**Comment by nYCSTs** [comment]
Oh, well I already have the build-essential package installed

**Comment by Almamu** [comment]
I've uploaded some changes to stop depending on std::filesystem that should fix this issue. Please reopen it if the problem persist.
