### ISSUE TITLE
FPS Arugument (option) doesn't work 

### ISSUE THREAD

**Issue by DashCruft** [Almamu/linux-wallpaperengine#66]
Hey there! I was trying to set the FPS for wallengine. However, it does not work and instead it returns just the help menu.

![image](https://user-images.githubusercontent.com/59381835/146126014-0bbdedc5-c7ff-496d-b74d-6537f62b0c79.png)

I also tried setting other values but the issue is still present.

**Comment by Almamu** [comment]
This should be fixed on commit a66bc26f1de0235101ce3d18140e18629a029331. Please re-open the issue if it still persists.
