### ISSUE TITLE
Can't clone the submodules

### ISSUE THREAD

**Issue by hamburgerghini1** [Almamu/linux-wallpaperengine#69]
![croppedscreenshot_20220130_102350](https://user-images.githubusercontent.com/98650216/151692429-ce92c938-9beb-4099-9e3f-86e06c5b951c.png)

**Comment by mihawk90** [comment]
This is a configuration issue on your side. GitHub does not recognise your SSH key.
Git can't even read the top-level repo, it doesn't even get to the submodules.

I suggest going through the [GitHub help](https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-ssh-urls) on this.

Alternatively you can use the HTTPS method instead, but it's a bit more convoluted:
```
git clone "https://github.com/Almamu/linux-wallpaperengine.git"
cd linux-wallpaperengine
git submodule set-url -- glfw "https://github.com/Almamu/glfw.git"
git submodule init
git submodule update
```

That way it *should* clone the submodule from the HTTPS path.

Realistically though, you should fix your configuration.

**Comment by Almamu** [comment]
That should fix the issue with cloning. I'll close it. If you still have issues with it please feel free to re-open it.
