### ISSUE TITLE
[BGFIX] Diagonal streaks across black background instead of wallpaper

### ISSUE THREAD

**Issue by FFuuZZuu** [Almamu/linux-wallpaperengine#79]
**Wallpaper Engine Background**
https://steamcommunity.com/sharedfiles/filedetails/?id=1911376783

**Console output**
No error in console.

**Screenshots**
I dont have a screenshot from windows, but there is a picture of how it should look on the workshop page, but it looks like this:
![image](https://user-images.githubusercontent.com/47675688/156049243-57eda767-1b7f-4caa-a715-96bb38cfdd47.png)

There are a few wallpapers that do the same thing (diagonal streaks across the screen), such as:

https://steamcommunity.com/sharedfiles/filedetails/?id=2208730574
![image](https://user-images.githubusercontent.com/47675688/156049510-6683ef7d-d015-4ff2-abeb-425398f8db8d.png)

https://steamcommunity.com/sharedfiles/filedetails/?id=1442116244
![image](https://user-images.githubusercontent.com/47675688/156049412-69b4ed61-3153-4d29-891e-dd210ca58856.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Desktop Environment: N/A
 - Window Manager: Awesome WM

**Additional context**
Other wallpapers do work, so it seems to be something that is unsupported in the wallpapers

**Comment by Almamu** [comment]
Those backgrounds seem to be simple "GIF"-like images. I'll look into it, shouldn't be too hard to fix.

**Comment by Almamu** [comment]
This should be supported properly on the latest version. I've had the background running for some time with success. Please re-open if this background still has issues.
