### ISSUE TITLE
Cannot initialize SDL audio system, SDL_GetError: Mixer not built with MP3 support

### ISSUE THREAD

**Issue by ahmedhnewa** [Almamu/linux-wallpaperengine#83]
I'm trying to load wallpaper of wallpaper engine steam program
I execute  the following command
./wallengine /home/username/.local/share/Steam/steamapps/workshop/content/431960/1674972620

but I get this error:

Detected scene.pkg file at /home/1772346090/.local/share/Steam/steamapps/workshop/content/431960/1674972620/scene.pkg. Adding to list of searchable pathsCannot initialize SDL audio system, SDL_GetError: Mixer not built with MP3 support

**Comment by mihawk90** [comment]
Can confirm the same here.

Compiled on Fedora, example background from README also without success:

```
[tarulia@localhost]/usr/bin/linux-wallpaperengine% ./wallengine /home/tarulia/Games/SteamLibrary/steamapps/workshop/content/431960/1845706469/
Detected scene.pkg file at /home/tarulia/Games/SteamLibrary/steamapps/workshop/content/431960/1845706469/scene.pkg. Adding to list of searchable paths
Cannot initialize SDL audio system, SDL_GetError: Mixer not built with MP3 support%
```

Window opens for a moment before it shuts down.

Running with `--silent` does fix the issue (obviously no audio then):
```
[tarulia@localhost]/usr/bin/linux-wallpaperengine% ./wallengine /home/tarulia/Games/SteamLibrary/steamapps/workshop/content/431960/1845706469/ --silent
Detected scene.pkg file at /home/tarulia/Games/SteamLibrary/steamapps/workshop/content/431960/1845706469/scene.pkg. Adding to list of searchable paths
[tarulia@localhost]/usr/bin/linux-wallpaperengine%
```

**Comment by Almamu** [comment]
I don't know why I thought SDLmixer initialization failing was a good reason to completely stop the process.

On fbc8b917ba342bfcdeecd8650bede5c0ec7064b9 I've added an error message so the background will run and display a warning in the console.

**Comment by mihawk90** [comment]
> maybe a different library would be a better candidate

Aren't we already depending on ffmpeg anyway? Couldn't that be used? Maybe mp3 support in ffmpeg is more common among distro packages?

On Fedora at least ffmpeg comes with mp3 support (via RPM Fusion):

```
[tarulia@localhost]~% ffmpeg -codecs | grep mp3
 DEAIL. mp3                  MP3 (MPEG audio layer 3) (decoders: mp3float mp3 ) (encoders: libmp3lame )
```

**Comment by mihawk90** [comment]
Already got a response on the bug report, well turns out I'm just stupid and there is already an SDL2 package :roll_eyes: 

So I tried building with that, but CMake can't find the SDL libs:

```
[...]
-- Found Threads: TRUE  
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find SDL (missing: SDL_LIBRARY SDL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindSDL.cmake:216 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:17 (find_package)


-- Configuring incomplete, errors occurred!
See also "/builddir/build/BUILD/linux-wallpaperengine/build/CMakeFiles/CMakeOutput.log".
See also "/builddir/build/BUILD/linux-wallpaperengine/build/CMakeFiles/CMakeError.log".
error: Bad exit status from /var/tmp/rpm-tmp.Bo5QZs (%build)
    Bad exit status from /var/tmp/rpm-tmp.Bo5QZs (%build)
```

So that makes me wonder are you using SDL 1.x or 2.x as a dependency? I guess 1 judging by it not finding the SDL2 lib?

**Comment by Almamu** [comment]
It should be using SDL1 as I also require the normal SDL library, as far as I know SDL2 packages have to start with "SDL2", mainly because there's a lot of software that relies on SDL1 being there.

The issue with using ffmpeg to play audio is that it only takes care of decoding the audio (as far as I know at least), and I do not have any experience with audio play on linux. I only know of OpenAL but I haven't really used it for anything yet...

**Comment by mihawk90** [comment]
> It should be using SDL1 as I also require the normal SDL library

Mh OK that's what I thought. So I imagine Debian has the same issue where the SMPEG library isn't available so SDL_Mixer can't be compiled with it.

> The issue with using ffmpeg to play audio is that it only takes care of decoding the audio (as far as I know at least)

Sounds about right, although ffplay is also part of ffmpeg, maybe that could be used?

**Comment by Almamu** [comment]
I'll take a look into ffplay because, being honest, I completely forgot about it.

**Comment by Almamu** [comment]
Looks like ffplay uses SDL2 so It should be fairly trivial to extract the audio-playing part of the code and implement it myself. For now looks like a promising option, so I'll keep looking into it.

**Comment by ahmedriad01** [comment]
> Looks like ffplay uses SDL2 so It should be fairly trivial to extract the audio-playing part of the code and implement it myself. For now looks like a promising option, so I'll keep looking into it.

Thank you very much for solving the bug, I tried to set the wallpaper as background using --screen-root but it didn't work and nothing change, you say "Only screens configured with the XRandr extension are supported" but I'm not sure how to configure my screen with xrandr in order to support Running as a screen's background

**Comment by Almamu** [comment]
Most distros using Xserver should automatically handle that for you through the settings app.

The main issue why --screen-root fails is most likely the desktop environment you're using. Some of them like to draw over the Xserver background, covering what this software draws.

**Comment by Almamu** [comment]
If there's any issue with the new audio playing code please feel free to open a new issue with the specific error.

**Comment by mihawk90** [comment]
Works perfectly for at least all these:

```
z% wallengine --fps 30 ~/.local/share/Steam/steamapps/workshop/content/431960/
Completing file
1391033800/  1845706469/  1883921173/  2274845251/  2429324929/  2787033447/  2788420872/
```

So nice one :+1:
