### ISSUE TITLE
[BGFIX] 2328113549 "Unsupported package version"

### ISSUE THREAD

**Issue by mihawk90** [Almamu/linux-wallpaperengine#85]
**Wallpaper Engine Background**
https://steamcommunity.com/sharedfiles/filedetails/?id=2328113549
https://steamcommunity.com/sharedfiles/filedetails/?id=1883921173
https://steamcommunity.com/sharedfiles/filedetails/?id=2788420872
https://steamcommunity.com/sharedfiles/filedetails/?id=2429324929
https://steamcommunity.com/sharedfiles/filedetails/?id=2787033447

**Console output**
```
[tarulia@localhost]/usr/bin/linux-wallpaperengine% ./wallengine --silent --fps 30 /home/tarulia/Games/SteamLibrary/steamapps/workshop/content/431960/2328113549
Failed to load scene.pkg file: Unsupported package version

[tarulia@localhost]/usr/bin/linux-wallpaperengine% ./wallengine --silent --fps 30 /home/tarulia/Games/SteamLibrary/steamapps/workshop/content/431960/1883921173
Failed to load scene.pkg file: Unsupported package version

[tarulia@localhost]/usr/bin/linux-wallpaperengine% ./wallengine --silent --fps 30 /home/tarulia/Games/SteamLibrary/steamapps/workshop/content/431960/2788420872
Failed to load scene.pkg file: Unsupported package version

[tarulia@localhost]/usr/bin/linux-wallpaperengine% ./wallengine --silent --fps 30 /home/tarulia/Games/SteamLibrary/steamapps/workshop/content/431960/2429324929
Failed to load scene.pkg file: Unsupported package version

[tarulia@localhost]/usr/bin/linux-wallpaperengine% ./wallengine --silent --fps 30 /home/tarulia/Games/SteamLibrary/steamapps/workshop/content/431960/2787033447
Failed to load scene.pkg file: Unsupported package version
```

**Screenshots**
none (unfortunately)

**Desktop (please complete the following information):**
 - OS: Fedora 33
 - Desktop Environment: KDE
 - Window Manager: [if in doubt, just leave it empty]

**Additional context**
none

PS: The "additional context" line is just cut off in https://github.com/Almamu/linux-wallpaperengine/blob/17d4be61b10b1fefb5eeeafe9111236947a69c85/.github/ISSUE_TEMPLATE/background-doesn-t-load-properly.md

**Comment by Almamu** [comment]
Package loading for all those backgrounds should be fixed. Some of them load, some have shader issues, these need individual investigation (and issues) on all of them.
