### ISSUE TITLE
[BGFIX] incorrect rendering of layer effect

### ISSUE THREAD

**Issue by mihawk90** [Almamu/linux-wallpaperengine#87]
**Wallpaper Engine Background(s)**
https://steamcommunity.com/sharedfiles/filedetails/?id=2787033447
https://steamcommunity.com/sharedfiles/filedetails/?id=2788420872

**Console output**
```
[tarulia@localhost]~/Development/SDL_mixer.spec% wallengine --fps 30 ~/.local/share/Steam/steamapps/workshop/content/431960/2788420872 
Detected scene.pkg file at /home/tarulia/.local/share/Steam/steamapps/workshop/content/431960/2788420872/scene.pkg. Adding to list of searchable paths
Found wallpaper engine's assets at /home/tarulia/.local/share/Steam/steamapps/common/wallpaper_engine/assets
Cannot initialize SDL audio system, SDL_GetError: Mixer not built with MP3 support
Continuing without audio support

[tarulia@localhost]~% wallengine --fps 30 ~/.local/share/Steam/steamapps/workshop/content/431960/2787033447
Detected scene.pkg file at /home/tarulia/.local/share/Steam/steamapps/workshop/content/431960/2787033447/scene.pkg. Adding to list of searchable paths
Found wallpaper engine's assets at /home/tarulia/.local/share/Steam/steamapps/common/wallpaper_engine/assets
Cannot initialize SDL audio system, SDL_GetError: Mixer not built with MP3 support
Continuing without audio support
```

**Screenshots**
Unfrortunately I don't have a Windows install to test on, however going by the Previews on Steam, the wavy-effect doesn't look right (or to be there at all):

![image1](https://steamuserimages-a.akamaihd.net/ugc/1840290902932092328/DA1F806233E790EE317D986A3853EF0ACCC2D4FF/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false)
![image2](https://steamuserimages-a.akamaihd.net/ugc/1840291226194149993/19A1E280DDB09675B28278C49C6C0D3EA00844A7/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false)

I'm assuming the wavy effect is supposed to be used as a displacement for the layer, not as a distortion on the entire layer. At least that would roughly match up with the movement in the preview.

On the second one the glow-effect on the sword also doesn't look right, but that probably requires a separate issue.

**Desktop (please complete the following information):**
 
- OS: Fedora 33
 - Desktop Environment: KDE
 - Window Manager:

**Comment by Almamu** [comment]
![imagen](https://user-images.githubusercontent.com/751307/162292573-f4d0ca15-f691-4c50-9a4b-024b8c48cf41.png)
In this situation looks like the background is missing those two masks in one of the shader passes, so most likely some of the code that handles texture loading/setup for shaders is wrong. I'm still looking into it, but I should be able to solve it soon.

**Comment by Almamu** [comment]
Should be fixed with the last commit, there were some codepaths that were not right and prevented some textures from being properly loaded and detected by the renderer. Should provide a better result now.
