### ISSUE TITLE
[BGFIX] Can not Running as a screen's background

### ISSUE THREAD

**Issue by EchoGroot** [Almamu/linux-wallpaperengine#88]
**Wallpaper Engine Background(s)**
2518958708

**Console output**

sudo ./wallengine --screen-root HDMI-A-0 /home/yuyy/.local/share/Steam/steamapps/workshop/content/431960/2518958708
Detected scene.pkg file at /home/yuyy/.local/share/Steam/steamapps/workshop/content/431960/2518958708/scene.pkg. Adding to list of searchable paths
Found assets folder alongside the binary: /opt/linux-wallpaperengine/seccond/linux-wallpaperengine/build/assets
Found requested screen: HDMI-A-0 -> 0x0:1920x1080
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
Cannot initialize SDL audio system, SDL_GetError: Mixer not built with MP3 support
Continuing without audio support

**Screenshots**

as same as not start this software

**Desktop (please complete the following information):**
 
```
             ............                yuyy@yuyy-pc 
         .';;;;;.       .,;,.            ------------ 
      .,;;;;;;;.       ';;;;;;;.         OS: Deepin 20.5 x86_64 
    .;::::::::'     .,::;;,''''',.       Host: 20Y7001KCD ThinkPad E14 Gen 3 
   ,'.::::::::    .;;'.          ';      Kernel: 5.15.24-amd64-desktop 
  ;'  'cccccc,   ,' :: '..        .:     Uptime: 3 days, 8 hours, 25 mins 
 ,,    :ccccc.  ;: .c, '' :.       ,;    Packages: 2380 (dpkg) 
.l.     cllll' ., .lc  :; .l'       l.   Shell: zsh 5.7.1 
.c       :lllc  ;cl:  .l' .ll.      :'   Resolution: 1920x1080 
.l        'looc. .   ,o:  'oo'      c,   DE: Deepin 
.o.         .:ool::coc'  .ooo'      o.   WM: KWin 
 ::            .....   .;dddo      ;c    Theme: deepin [GTK2/3] 
  l:...            .';lddddo.     ,o     Icons: Papirus [GTK2/3] 
   lxxxxxdoolllodxxxxxxxxxc      :l      Terminal: deepin-terminal 
    ,dxxxxxxxxxxxxxxxxxxl.     'o,       CPU: AMD Ryzen 5 5500U with Radeon Graphics (12) @ 2.100GHz 
      ,dkkkkkkkkkkkkko;.    .;o;         GPU: AMD ATI Device 164c 
        .;okkkkkdl;.    .,cl:.           Memory: 11307MiB / 14880MiB 
            .,:cccccccc:,.

```

**Additional context**

Any additional information about your setup

**Comment by EchoGroot** [comment]
Running in a window is work
```
sudo ./wallengine /home/yuyy/.local/share/Steam/steamapps/workshop/content/431960/2518958708
Detected scene.pkg file at /home/yuyy/.local/share/Steam/steamapps/workshop/content/431960/2518958708/scene.pkg. Adding to list of searchable paths
Found assets folder alongside the binary: /opt/linux-wallpaperengine/seccond/linux-wallpaperengine/build/assets
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
Cannot initialize SDL audio system, SDL_GetError: Mixer not built with MP3 support
Continuing without audio support
```

![image](https://user-images.githubusercontent.com/44628981/164429716-509f4d40-9452-40d1-af04-48db777f0c6e.png)

**Comment by mihawk90** [comment]
Are you sure nothing else is drawing to the background? The README mentions this:

> IMPORTANT: Right now this doesn't work if there is anything drawing to the background (like a compositor, nautilus, etc)

Most desktops already draw to the background by default.

**Comment by Almamu** [comment]
Progress on supporting Desktop Environments/other compositors is an ongoing task that'll take time... The progress on this is tracked under #8
