### ISSUE TITLE
[Feature Request] wallpaper resize to fit

### ISSUE THREAD

**Issue by arthurmelton** [Almamu/linux-wallpaperengine#90]
I personally would really like a feature like this because one of my monitors are 1920x1200 so its harder to find wallpapers I like that fit to that resolution, this is an example of what currently happens 
![image](https://user-images.githubusercontent.com/29708070/166089547-3fd5e163-bf62-4fe2-bd97-0f9c7c699066.png)
and this is what it should look like 
![image](https://user-images.githubusercontent.com/29708070/166089519-06ae85bb-2d46-4b19-adc1-a213121e13f0.png)
It would be really nice if the image could resize so it would fit on my monitor, this also gets referenced as `zoomed fill` and if this is a bug this is what I am using
- Arch linux
- Xmonad 0.15
- Picom vgit-7e568
ps. thank you for doing this, you are a legend

**Comment by Almamu** [comment]
Could you share the workshop id or a link of the wallpaper so I can look closer into it? I do have some 1080p panels to try this.

**Comment by AMTitan** [comment]
well this happens for every wallpaper that is not 16:10

**Comment by AMTitan** [comment]
here is the link https://steamcommunity.com/sharedfiles/filedetails/?id=1134328086 though

**Comment by Almamu** [comment]
I've looked at some backgrounds designed for different aspect ratios and all scale to fill the current screen space available so there's no blackbars, that's why the wolf's background looks bigger. I can implement different scaling modes so you can alter this behaviour, with the cost of having extra black bars either on top or on the sides, but I don't see any other option.

**Comment by AMTitan** [comment]
So the result I was thinking about is to make it so it has the black bars but then zoom in so you wont see the black bars, this will make it so you cant see as much of the wallpaper but then no black bars.

**Comment by Almamu** [comment]
That's how it should be working right now. This is how it looks in my 1080x1920 screen:
![image](https://user-images.githubusercontent.com/751307/167278263-2455514b-ac5b-451c-b905-5e1d56566123.png)

And this is how it looks on a 1080p display:
![image](https://user-images.githubusercontent.com/751307/167278272-21c8e813-f06e-4dcf-af00-3643563bfd8e.png)

Unless I'm missing something the background is scaled in both directions to fill the longer side of the display, so there's no black bars.

**Comment by AMTitan** [comment]
No, I mean that it will keep the same ratio but it will zoom in so it does not have black bars so instead of it being streached it would look like 
![image](https://user-images.githubusercontent.com/29708070/167314513-c2536854-8da3-4a20-afc0-08ec405169fa.png)
so you wont be able to see the edges but it will look normal

**Comment by Almamu** [comment]
It should be keeping the right aspect ratio, but looks like something in my calculations is not right. This might be related to #81 too as It just dawned on me that the only way for a background to look pixelated is to have some kind of scaling being applied, and the different sizes is the only way for that to happen.

**Comment by Pasalc** [comment]
@arthurmelton Hello, if you're still using this software, could you check that this pull request works for you? You should be able to run `zoom fill` like this:
`./wallengine --scaling fill --screen-root YOUR_SCREEN 1134328086`

**Comment by arthurmelton** [comment]
I actually don't use this software anymore and don't have a steam account to use the software anymore. I will promptly close this issue as I am not following this issue anymore.
