### ISSUE TITLE
wallengine quit's when changing settings for desktop symbols

### ISSUE THREAD

**Issue by Martin1995** [Almamu/linux-wallpaperengine#91]
I don't know if it's a bug or not, but I just found out if you change the desktop symbols from hidden to shown with MATE Tweak on MATE Desktop it crashes/quits out wallengine with the message `X connection to :0 broken (explicit kill or server shutdown).`

I can't tell if it's intended behavior and what's happening in the background so I just opened this issue to be safe, because if it's a reall issue it can be adressed faster.

**Comment by Almamu** [comment]
I'll have to investigate this one a bit more closely. IMO the wallpaper should be able to refresh whatever X resources needed if there's any change in them.

**Comment by Almamu** [comment]
I've added some error handling to the background and it should be able to recover from these errors in most instances. Please let me know if the background keeps disappearing when changing settings like the ones you were having issues with.

**Comment by Martin1995** [comment]
Sorry for answering 6 Day's later. It at least isn't crashing out anymore, but as long as the desktop symbols are hidden, which is my default setting, it is displaying as intended. When I have the desktop symbols visible I only see my static wallpaper but not the animated one from wallengine which is still running in the background.

I have made a video and made it accessible through the following web address [https://kmwg.moe/webroot/sharepoint/2022-05-14%2022-22-19.mp4](url)

**Comment by Martin1995** [comment]
ah ok, thank you for clarifying that this behaviour is not a bug, but a feature of the interfacing between the DE and wallengine.
