### ISSUE TITLE
Detected X error

### ISSUE THREAD

**Issue by eyalmazuz** [Almamu/linux-wallpaperengine#94]
I'm trying to run the engine as the guide says with the example wallpaper
but all I see is the screen opens the wallpaper engine window for a millisecond with a black screen, then it crashes, and gets the following output but the software keeps running
![image](https://user-images.githubusercontent.com/34383384/167473099-4e081ab7-f201-4583-a96b-4d1e27e60e44.png)

when running through gdb it does the same thing and gets stuck at the same spot without getting any segfault or errors

**Comment by Almamu** [comment]
Most likely the Desktop Environment you're using takes ownership of the background drawing and is conflicting with linux-wallpaperengine. I've added X error reporting back but I don't think it'll be of much more use for now. There's still lots of features left to be implemented, and extensive DE support is one of them :/

**Comment by eyalmazuz** [comment]
Hi, thank you for the response
I realized I forgot to upload my system information so here it is
![image](https://user-images.githubusercontent.com/34383384/167577755-90876816-ee1b-4a6e-906a-56d862c39cc3.png)

I downloaded the new version with the reporting back and I see that my issue is similar to #80 
![image](https://user-images.githubusercontent.com/34383384/167577673-549daaac-6f9b-43a2-8839-3f6521872f0b.png)

**Comment by Almamu** [comment]
This seems to be related to #8. The progress on support for Desktop Enviroment's is being tracked in that issue.
