### ISSUE TITLE
No REQUIRED_VARS specified for FIND_PACKAGE_HANDLE_STANDARD_ARGS()

### ISSUE THREAD

**Issue by Kazaflow** [Almamu/linux-wallpaperengine#95]
When I try "cmake .."  it spits out this error:
![Screenshot from 2022-05-15 17-43-48](https://user-images.githubusercontent.com/105598805/168481885-d5b01136-805a-4850-9465-9cc91ce2c0ed.png)
I followed the instructions and installed all the packages and moved the assets folder to where the main.cpp is.

**Comment by 1235467** [comment]
I got into just the same problem here.Tested on ubuntu 20.04 both on azure server and my laptop.

**Comment by OposDev** [comment]
Is FFmpeg installed? 
![image](https://user-images.githubusercontent.com/58175621/176122468-be3dc51c-b931-41ae-930c-b59d35cf63c1.png)
It looks like Cmake can't find FFmpeg.
