### ISSUE TITLE
Gifs don't loop

### ISSUE THREAD

**Issue by UltraBlackLinux** [Almamu/linux-wallpaperengine#99]
Hey there,
I've been using a gif as a wallpaper for quite a while now, but whatever gif I use, they always stop looping after a short while or just don't even start doing so in the first place.
Is this not yet implemented and thus intended?
Thanks!

**Comment by UltraBlackLinux** [comment]
I didn't get a bugreport template.

**Comment by UltraBlackLinux** [comment]
Here is my current wallpaper: [2466530208](https://steamcommunity.com/sharedfiles/filedetails/?id=2466530208)

**Comment by Almamu** [comment]
@UltraBlackLinux I've had the background running for half and hour without any issue so I'd say that most likely the app is crashing. Could you run it from your terminal and once the background has stopped playing check if it's still running? most likely that's what's happening...

**Comment by UltraBlackLinux** [comment]
I just checked; The gif just stops looping while the process continues to run. I tried debugging this with gdb, but I'm too inexperienced to use it properly.

In the process I noticed, that I was not up to date, pulled the recent changes and rebuilt wallpaperengine. Now it works. I am sorry, that I didn't check this earlier!
